# Generated by Django 3.2 on 2023-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activists',
            fields=[
                ('activist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event_ids', models.JSONField()),
                ('image_ids', models.JSONField()),
                ('tribal_affiliation', models.JSONField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_birth_accuracy', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='YEAR', max_length=5)),
                ('latitude_of_birth', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_of_birth', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date_of_death', models.DateField()),
                ('date_of_death_accuracy', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='YEAR', max_length=5)),
                ('short_bio', models.CharField(max_length=10000)),
                ('long_bio', models.CharField(max_length=10000)),
                ('citations', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'activists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('map', models.BooleanField()),
                ('start_date', models.DateField()),
                ('start_date_accuracy', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='YEAR', max_length=5)),
                ('end_date', models.DateField()),
                ('end_date_accuracy', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='YEAR', max_length=5)),
                ('issue_types', models.JSONField()),
                ('short_description', models.CharField(max_length=10000)),
                ('long_description', models.CharField(max_length=10000)),
                ('citations', models.CharField(max_length=10000)),
                ('activist_ids', models.JSONField()),
                ('related_event_ids', models.JSONField()),
                ('image_ids', models.JSONField()),
                ('location_names', models.JSONField()),
                ('location_data', models.JSONField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('header_url', models.URLField()),
                ('timeline_url', models.CharField(max_length=10000)),
                ('alt_text', models.CharField(max_length=10000)),
                ('caption', models.CharField(max_length=10000)),
                ('credit', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
